// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WestCoastEducation.Data;

namespace WestCoastEducation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210518110938_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WestCoastEducation.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseInformation")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("CourseName")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<DateTime?>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("Id");

                    b.ToTable("Course", "Courses");
                });

            modelBuilder.Entity("WestCoastEducation.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("Country")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("VARCHAR(12)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("VARCHAR(12)");

                    b.Property<short>("StreetNumber")
                        .HasColumnType("SMALLINT");

                    b.HasKey("Id");

                    b.ToTable("Student", "Students");
                });
#pragma warning restore 612, 618
        }
    }
}
